version: '3'
services:
  php_tester:
    build: ./php
    image: php:latest
    container_name: php_tester
    hostname: "php_tester"
    restart: always
    volumes:
      - ./restoran_project_kel9:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - mysql_tester

  mysql_tester:
    image: mariadb:10.2
    container_name: mysql_tester
    restart: unless-stopped
    tty: true
    ports:
      - "33309:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: Djony
      MYSQL_PASSWORD: Djony!!
      MYSQL_ROOT_PASSWORD: Djony
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
    read_only: false

  nginx_tester:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_tester
    restart: always
    hostname: "nginx"
    ports:
      - "82:80"
    volumes:
      - ./restoran_project_kel9:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_tester

  # mailpit:
  #   container_name: mailpit
  #   restart: unless-stopped
  #   volumes:
  #     - ./mailpit-data:/data
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  #   environment:
  #     - MP_MAX_MESSAGES=5000
  #     - MP_DATABASE=/data/mailpit.db
  #     - MP_SMTP_AUTH_ACCEPT_ANY=1
  #     - MP_SMTP_AUTH_ALLOW_INSECURE=1
  #     - TZ=Europe/Madrid

